quiet = "--quiet" %in% commandArgs(FALSE)
formats = commandArgs(TRUE)

# provide default formats if necessary
if (length(formats) == 0) formats = c('bookdown::gitbook')
# render the book to all formats unless they are specified via command-line args
for (fmt in formats) {
  cmd = sprintf("bookdown::render_book('index.Rmd', '%s', quiet = %s)", fmt, quiet)
  res = bookdown:::Rscript(c('-e', shQuote(cmd)))
  if (res != 0) stop('Failed to compile the book to ', fmt)
}
unlink('rmarkdown-cookbook.log')


# creates redirects
redirect = function(from, to) {
  # to = paste0('https://www.tornil.me/these/', to)
  writeLines(sprintf(
    '<html><head><meta http-equiv="refresh" content="0; URL=\'%s\'" /></head><body><script>window.location = "%s";</script></html>', to, to
  ), paste0('_dist/', from))
}


redirect('002-sommaire.html', 'index.html')
redirect('003-remerciements.html', 'index.html#remerciements')
redirect('004-introduction.html', 'introduction.html')
redirect('005-chapitre-1-sommaire.html', 'le-syst%C3%A8me-haptique-de-lhomme.html')
redirect('005-chaptitre-1-sommaire.html', 'le-syst%C3%A8me-haptique-de-lhomme.html')
redirect('006-introduction.html', 'le-syst%C3%A8me-haptique-de-lhomme.html#introduction-1')
redirect('007-le-systeme-haptique-cote-perception-la-somesthesie.html', 'le-syst%C3%A8me-haptique-de-lhomme.html#somesthesie')
redirect('008-le-systeme-haptique-cote-action-le-systeme-moteur.html', 'le-syst%C3%A8me-haptique-de-lhomme.html#moteur')
redirect('009-l-exploration-haptique-quand-l-action-et-la-perception-se-conjuguent-sur-le-canal-haptique.html', 'le-syst%C3%A8me-haptique-de-lhomme.html#conjuguent')
redirect('010-conclusion.html', 'le-syst%C3%A8me-haptique-de-lhomme.html#conclusion')
redirect('011-chapitre-2-communications-homme-machine.html', 'communications-homme-machine.html')
redirect('011-chaptitre-1-communications-homme-machine.html', 'communications-homme-machine.html')
redirect('011-chaptitre-2-communications-homme-machine.html', 'communications-homme-machine.html')
redirect('012-introduction.html', 'communications-homme-machine.html#introduction-2')
redirect('013-les-systemes-interactifs.html', 'communications-homme-machine.html#les-syst%C3%A8mes-interactifs')
redirect('014-les-modeles-de-l-utilisateur.html', 'communications-homme-machine.html#les-mod%C3%A8les-de-lutilisateur')
redirect('015-les-peripheriques-d-entree.html', 'communications-homme-machine.html#les-p%C3%A9riph%C3%A9riques-dentr%C3%A9e')
redirect('016-les-peripheriques-de-sortie-a-retour-haptique.html', 'communications-homme-machine.html#les-p%C3%A9riph%C3%A9riques-de-sortie-%C3%A0-retour-haptique')
redirect('017-les-applications-du-retour-haptique.html', 'communications-homme-machine.html#les-applications-du-retour-haptique')
redirect('018-conclusion.html', 'communications-homme-machine.html#conclusion-1')
redirect('019-chapitre-3-performances-du-retour-de-force-sur-le-pointage.html', 'performances-du-retour-de-force-sur-le-pointage.html')
redirect('019-chaptitre-3-performances-du-retour-de-force-sur-le-pointage.html', 'performances-du-retour-de-force-sur-le-pointage.html')
redirect('020-introduction-ameliorer-la-vitesse-de-pointage.html', 'performances-du-retour-de-force-sur-le-pointage.html#introduction-am%C3%A9liorer-la-vitesse-de-pointage')
redirect('021-travaux-anterieurs-integrant-le-retour-d-effort-dans-une-tache-de-pointage.html', 'performances-du-retour-de-force-sur-le-pointage.html#travaux-ant%C3%A9rieurs-int%C3%A9grant-le-retour-deffort-dans-une-t%C3%A2che-de-pointage')
redirect('022-protocole-de-test.html', 'performances-du-retour-de-force-sur-le-pointage.html#protocole-de-test')
redirect('023-resultats-et-discussion.html', 'performances-du-retour-de-force-sur-le-pointage.html#r%C3%A9sultats-et-discussion')
redirect('024-conclusion.html', 'performances-du-retour-de-force-sur-le-pointage.html#conclusion-2')
redirect('025-chapitre-4-vers-l-accessibilite.html', 'vers-laccessibilit%C3%A9.html')
redirect('025-chaptitre-4-vers-l-accessibilite.html', 'vers-laccessibilit%C3%A9.html')
redirect('026-introduction.html', 'vers-laccessibilit%C3%A9.html#introduction-3')
redirect('027-l-interaction-non-visuelle.html', 'vers-laccessibilit%C3%A9.html#linteraction-non-visuelle')
redirect('028-l-accessibilite-definitions.html', 'vers-laccessibilit%C3%A9.html#laccessibilit%C3%A9-d%C3%A9finitions')
redirect('029-l-accessibilite-des-personnes-non-voyantes-et-mal-voyantes-grace-a-un-dispositif-a-retour-haptique.html', 'vers-laccessibilit%C3%A9.html#laccessibilit%C3%A9-des-personnes-non-voyantes-et-mal-voyantes-gr%C3%A2ce-%C3%A0-un-dispositif-%C3%A0-retour-haptiquetitre')
redirect('030-recommandations-de-conception.html', 'vers-laccessibilit%C3%A9.html#recommandations-de-conception')
redirect('030-recommandations-de-conceptions.html', 'vers-laccessibilit%C3%A9.html#recommandations-de-conception')
redirect('031-conclusion.html', 'vers-laccessibilit%C3%A9.html#conclusion-3')
redirect('032-chapitre-5-la-localisation-relative.html', 'la-localisation-relative.html')
redirect('032-chaptitre-5-la-localisation-relative.html', 'la-localisation-relative.html')
redirect('033-introduction.html', 'la-localisation-relative.html#introduction-4')
redirect('034-la-localisation-relative.html', 'la-localisation-relative.html#la-localisation-relative-1')
redirect('035-application-a-la-geographie-geogr-haptique.html', 'la-localisation-relative.html#geogrhaptique')
redirect('036-application-a-la-musique-music-haptic.html', 'la-localisation-relative.html#application-%C3%A0-la-musique-musichaptic')
redirect('037-conclusion.html', 'la-localisation-relative.html#conclusion-5')
redirect('038-chapitre-6-conclusion-et-perspectives.html', 'conclusion-et-perspectives.html')
redirect('038-chaptitre-5-conclusion-et-perspectives.html', 'conclusion-et-perspectives.html')
redirect('038-chaptitre-6-conclusion-et-perspectives.html', 'conclusion-et-perspectives.html')
redirect('039-des-dispositifs-des-interactions-de-l-accessibilite.html', 'conclusion-et-perspectives.html#des-dispositifs-des-interactions-de-laccessibilit%C3%A9')
redirect('040-pour-aller-plus-loin.html', 'conclusion-et-perspectives.html#pour-aller-plus-loin')
redirect('041-annexes.html', 'annexes.html')
redirect('042-la-feuille-de-style-xsl-pour-transformer-du-cml-en-svg.html', 'annexes.html#la-feuille-de-style-xsl-pour-transformer-du-cml-en-svg')
redirect('043-les-technologies-utilisees.html', 'annexes.html#les-technologies-utilis%C3%A9es')
redirect('044-le-phantom.html', 'annexes.html#le-phantom')
redirect('045-la-web-accessibility-initiative-(wai)-du-world-wide-web-consortium-(w3c).html', 'annexes.html#accessibilite')
redirect('046-asynchronous-javascript-and-xml-ajax.html', 'annexes.html#ajax')
redirect('047-bibliographie.html', 'bibliographie.html')
redirect('index.html', 'index.html')
